var miApp = angular.module('bancoApp', [] );

	miApp.controller('datosBanco', function($scope){
		$scope.datos = [
{"numero":"007","banco":"Banco Galicia", "contacto": "adrian.g.dagostino@bancogalicia.com.ar"},
{"numero":"011","banco":"Banco Nacion"},
{"numero":"014","banco":"Banco Provincia"},
{"numero":"015","banco":"Banco ICBC"},
{"numero":"016","banco":"Banco Citi"},
{"numero":"017","banco":"Banco Frances"},
{"numero":"018","banco":"Banco Tokyo MitsubishiUFJ"},
{"numero":"020","banco":"Banco de Cordoba"},
{"numero":"027","banco":"Banco Superville"},
{"numero":"029","banco":"Banco Ciudad"},
{"numero":"034","banco":"Banco Patagonia"},
{"numero":"044","banco":"Banco Hipotecario"},
{"numero":"045","banco":"Banco San Juan"},
{"numero":"046","banco":"Banco de Brasil"},
{"numero":"060","banco":"Banco de Tucuman"},
{"numero":"065","banco":"Banco Municipal"},
{"numero":"072","banco":"Banco Santander Rio"},
{"numero":"079","banco":"Banco de Cuyo"},
{"numero":"083","banco":"Banco del Chubut"},
{"numero":"086","banco":"Banco de Santa Cruz"},
{"numero":"093","banco":"Banco de La Pampa"},
{"numero":"094","banco":"Banco de Corrientes"},
{"numero":"097","banco":"Banco Provincia del Neuquen"},
{"numero":"150","banco":"Banco HSBC"},
{"numero":"191","banco":"Banco Credicoop"},
{"numero":"198","banco":"Banco de Valores"},
{"numero":"254","banco":"Banco Mariva"},
{"numero":"259","banco":"Banco Itau"},
{"numero":"266","banco":"BNP Paribas"},
{"numero":"268","banco":"Banco de Tierra del Fuego"},
{"numero":"269","banco":"Banco de la Republica Oriental del Uruguay"},
{"numero":"277","banco":"Banco Saenz"},
{"numero":"281","banco":"Banco Meridian"},
{"numero":"285","banco":"Banco Macro"},
{"numero":"299","banco":"Banco Comafi"},
{"numero":"301","banco":"Banco Piano"},
{"numero":"303","banco":"Banco Finansur"},
{"numero":"305","banco":"Banco Julio"},
{"numero":"309","banco":"Banco de La Rioja"},
{"numero":"310","banco":"Banco del Sol"},
{"numero":"311","banco":"Banco del Chaco"},
{"numero":"315","banco":"Banco Formosa"},
{"numero":"319","banco":"Banco CMF"},
{"numero":"321","banco":"Banco Santiago del Estero"},
{"numero":"322","banco":"Banco Industrial"},
{"numero":"325","banco":"Deutsche Bank"},
{"numero":"330","banco":"Banco de Santa Fe"},
{"numero":"331","banco":"Banco Cetelem"},
{"numero":"332","banco":"Banco de Servicios Financieros"},
{"numero":"335","banco":"Banco Cofidis"},
{"numero":"336","banco":"Banco Bradesco"},
{"numero":"338","banco":"Banco de Servicios y Transacciones"},
{"numero":"341","banco":"Banco Masventas"},
{"numero":"386","banco":"Banco de Entre Rios"},
{"numero":"388","banco":"Banco Bisel"},
{"numero":"389","banco":"Banco Columbia"},
{"numero":"415","banco":"Multifinanzas"},
{"numero":"432","banco":"Banco de Comercio"}];
})