var miApp = angular.module('sucuApp', ['ngclipboard'] );
	
	miApp.controller('datosSucus', function($scope) {
		$scope.datos = [{"sucursal":"01 – Casa Central","nombre":"BENNARDIS  Teofilo Domingo","puesto":"Jefe Operativo","interno":"27106","email":"dbennardis@bancoindustrial.com.ar"},
{"sucursal":"01 – Casa Central","nombre":"MERLO  Gabriela Paula","puesto":"Asistente","interno":"27386","email":"gmerlo@bancoindustrial.com.ar"},
{"sucursal":"01 – Casa Central","nombre":"MUSANTE  Gustavo Ezequiel","puesto":"Gerente de Sucursal","interno":"27130","email":"gmusante@bancoindustrial.com.ar"},
{"sucursal":"01 – Casa Central","nombre":"ZABALA  Marcelo Alberto","puesto":"Jefe de Sector","interno":"27804","email":"mzabala@bancoindustrial.com.ar"},
{"sucursal":"01 – Casa Central","nombre":"MANSILLA Romina Alejandra","puesto":"Cajas de Seguridad","interno":"27182","email":"rmansilla@bancoindustrial.com.ar"},
{"sucursal":"01 – Casa Central","nombre":"TORRES Matias Ezequiel","puesto":"Tesoreria ","interno":"27146","email":"etorres@bancoindustrial.com.ar"},
{"sucursal":"03 - Casa Matriz Azul","nombre":"GOYENECHE  Adrian Andres","puesto":"Gerente de Sucursal","interno":"30200","email":"agoyeneche@bancoindustrial.com.ar"},
{"sucursal":"03 - Casa Matriz Azul","nombre":"BARONI  Horacio Alberto","puesto":"Jefe Operativo","interno":"30214","email":"hbaroni@bancoindustrial.com.ar"},
{"sucursal":"03 - Casa Matriz Azul","nombre":"LUNA  Hugo Alberto","puesto":"Tesorero de Sucursal","interno":"30212","email":"vacio"},
{"sucursal":"03 - Casa Matriz Azul","nombre":"ROSA Jorge","puesto":"Analista","interno":"30222","email":"jrosa@bancoindustrial.com.ar"},
{"sucursal":"15 – General Lamadrid","nombre":"DE BULNES  Nestor Marcelo","puesto":"Gerente de Sucursal","interno":"2286 42 0314","email":"ndebulnes@bancoindustrial.com.ar"},
{"sucursal":"15 – General Lamadrid","nombre":"IPARRAGUIRRE Lucrecia","puesto":"Jefe Operativo","interno":"2286 42 0314","email":"liparraguirre@bancoindustrial.com.ar"},
{"sucursal":"20 – Tandil","nombre":"BALLESTEROS  Mariana Estela","puesto":"Jefe Operativo","interno":"20202","email":"mballesteros@bancoindustrial.com.ar"},
{"sucursal":"20 – Tandil","nombre":"IRIGOYEN  Horacio Daniel","puesto":"Tesorero de Sucursal","interno":"20201","email":"vacio"},
{"sucursal":"20 – Tandil","nombre":"VALLE  Luis Hernan","puesto":"Gerente de Sucursal","interno":"20200","email":"lvalle@bancoindustrial.com.ar"},
{"sucursal":"20 – Tandil","nombre":"ERRANDOSORO Sonia Ines","puesto":"","interno":"20203","email":"serrandosoro@bancoindustrial.com.ar"},
{"sucursal":"21 – Balcarce","nombre":"LARRONDO  Nestor Simon","puesto":"Tesorero de Sucursal","interno":"21210","email":"vacio"},
{"sucursal":"21 – Balcarce","nombre":"MARTORELLO  Gustavo Ernesto","puesto":"Jefe Operativo","interno":"21204","email":"gmartorello@bancoindustrial.com.ar"},
{"sucursal":"21 – Balcarce","nombre":"TRAPANI  Maria Cristina","puesto":"Gerente de Sucursal","interno":"21200","email":"mtrapani@bancoindustrial.com.ar"},
{"sucursal":"22 – Mar del Plata (22)","nombre":"BIANCHI  Guillermo Armando","puesto":"Jefe Operativo","interno":"22201","email":"gbianchi@bancoindustrial.com.ar"},
{"sucursal":"22 – Mar del Plata (22)","nombre":"CORIO  Mariano Alberto","puesto":"Tesorero de Sucursal","interno":"22202","email":"mcorio@bancoindustrial.com.ar"},
{"sucursal":"22 – Mar del Plata (22)","nombre":"LEALI  Claudio Norberto","puesto":"Gerente de Centro de Servicios","interno":"22200","email":"cleali@bancoindustrial.com.ar"},
{"sucursal":"23  -La Plata (23)","nombre":"RECOFSKY  Carina Gisela","puesto":"Jefe de Area","interno":"221 489 6759","email":"crecofsky@bancoindustrial.com.ar"},
{"sucursal":"23 – La Plata (23)","nombre":"BIANCHI  Pablo Jose","puesto":"Gerente de Centro de Servicios","interno":"221 489 6759","email":"pbianchi@bancoindustrial.com.ar"},
{"sucursal":"23 – La Plata (23)","nombre":"DIAZ  Guillermo Antonio","puesto":"Jefe Operativo","interno":"221 489 6759","email":"gdiaz@bancoindustrial.com.ar"},
{"sucursal":"23 – La Plata (23)","nombre":"LUPI  Germán Gustavo","puesto":"Tesorero de Sucursal","interno":"221 489 6759","email":"glupi@bancoindustrial.com.ar"},
{"sucursal":"24 – Junin","nombre":"AVALLE  Claudio Javier","puesto":"Gerente de Sucursal","interno":"24200","email":"cavalle@bancoindustrial.com.ar"},
{"sucursal":"24 – Junin","nombre":"GONZALEZ  Sergio Hector","puesto":"Tesorero de Sucursal","interno":"24205","email":"vacio"},
{"sucursal":"24 – Junin","nombre":"WASSI  Carlos Mario","puesto":"Jefe Operativo","interno":"24204","email":"cwassi@bancoindustrial.com.ar"},
{"sucursal":"24 – Junin","nombre":"PICCHI Maria Nelida","puesto":"_","interno":"24202","email":"mpicchi@bancoindustrial.com.ar"},
{"sucursal":"25 – Bahia Blanca","nombre":"CRISTOBO  Esteban Oscar","puesto":"Tesorero de Sucursal","interno":"25203","email":"ecristobo@bancoindustrial.com.ar"},
{"sucursal":"25 – Bahia Blanca","nombre":"MAYZE  Romina","puesto":"Gerente de Centro de Servicios","interno":"25200","email":"rmayze@bancoindustrial.com.ar"},
{"sucursal":"25 – Bahia Blanca","nombre":"ROMERO  Yesica Verónica","puesto":"Jefe Operativo","interno":"25202","email":"yromero@bancoindustrial.com.ar"},
{"sucursal":"25 – Bahia Blanca","nombre":"MACIARELLO Pablo Fabian","puesto":"","interno":"25208","email":"pmaciariello@bancoindustrial.com.ar"},
{"sucursal":"26 – Recoleta / Palermo","nombre":"DE MAIO Miriam Hebe","puesto":"Jefe Operativo","interno":"26201","email":"mdemaio@bancoindustrial.com.ar"},
{"sucursal":"26 – Recoleta / Palermo","nombre":"BAZZANO Valeria","puesto":"Gerente de sucursal","interno":"26200","email":"mlebron@bancoindustrial.com.ar"},
{"sucursal":"26 – Recoleta / Palermo","nombre":"MARTINEZ PESTAÑA  Natalia","puesto":"Tesorero de Sucursal","interno":"26211","email":"nmartinez@bancoindustrial.com.ar"},
{"sucursal":"27 – Cordoba","nombre":"PAJON  Analia Beatríz","puesto":"Jefe Operativo","interno":"27901","email":"apajon@bancoindustrial.com.ar"},
{"sucursal":"27 – Cordoba","nombre":"RATTI  Marcelo Julio","puesto":"Tesorero de Sucursal","interno":"27911","email":"mratti@bancoindustrial.com.ar"},
{"sucursal":"27 – Cordoba","nombre":"YANNELLI Carlos Alberto","puesto":"Gerente de Centro de Servicios","interno":"27900","email":"cyannelli@bancoindustrial.com.ar"},
{"sucursal":"27 – Cordoba","nombre":"BASILICO Jose Maria","puesto":"","interno":"27908","email":"jbasilico@bancoindustrial.com.ar"},
{"sucursal":"31 – Salta","nombre":"CINTIONI  Ariel Dario","puesto":"Jefe Operativo","interno":"31201","email":"acintioni@bancoindustrial.com.ar"},
{"sucursal":"31 – Salta","nombre":"IBARRA  Juan Pablo","puesto":"Gerente de Sucursal","interno":"31200","email":"jibarra@bancoindustrial.com.ar"},
{"sucursal":"31 – Salta","nombre":"MEDINA  Miguel Angel","puesto":"Tesorero de Sucursal","interno":"31200","email":"vacio"},
{"sucursal":"32 – Cordoba Centro","nombre":"CASA  Jorge Javier","puesto":"Jefe Operativo","interno":"32201","email":"jcasa@bancoindustrial.com.ar"},
{"sucursal":"32 – Cordoba Centro","nombre":"JOHNSTON  Valeria","puesto":"Gerente de Sucursal","interno":"32207","email":"vacio"},
{"sucursal":"32 – Cordoba Centro","nombre":"VEGA  Jorge Raul","puesto":"Tesorero de Sucursal","interno":"32203","email":"vjohnston@bancoindustrial.com.ar"},
{"sucursal":"32 – Cordoba Centro","nombre":"CASTELLO Luis","puesto":"_","interno":"32202","email":"hcastello@bancoindustrial.com.ar"},
{"sucursal":"33 – Rosario","nombre":"LEONI Pablo Alejandro","puesto":"Tesorero de Sucursal","interno":"33203","email":"vacio"},
{"sucursal":"33 – Rosario","nombre":"PALAIKIS Leonardo Ruben","puesto":"Jefe Operativo","interno":"33201","email":"lpalaikis@bancoindustrial.com.ar"},
{"sucursal":"33 – Rosario","nombre":"PROFETA Miguel Angel","puesto":"Gerente de Sucursal","interno":"33200","email":"mprofeta@bancoindustrial.com.ar"},
{"sucursal":"34 – Mendoza","nombre":"DE MEZZO Gustavo Valentin","puesto":"Gerente de Sucursal","interno":"34200","email":"gdemezzo@bancoindustrial.com.ar"},
{"sucursal":"34 – Mendoza","nombre":"QUIROGA Alejandro Nicolas","puesto":"Tesorero de Sucursal","interno":"34210","email":"vacio"},
{"sucursal":"34 – Mendoza","nombre":"SEDANO Sergio Sebastian","puesto":"Jefe Operativo","interno":"34208","email":"ssedano@bancoindustrial.com.ar"},
{"sucursal":"34 – Mendoza","nombre":"LA MALFA Cristian Daniel","puesto":"","interno":"34205","email":"clamalfa@bancoindustrial.com.ar"},
{"sucursal":"35 – Tucuman (35)","nombre":"GARCIA CAINZO  Hector Raimundo","puesto":"Tesorero de Sucursal","interno":"35202","email":"vacio"},
{"sucursal":"35 – Tucuman (35)","nombre":"MARENGO  Atilio Esteban","puesto":"Gerente de Sucursal","interno":"35200","email":"amarengo@bancoindustrial.com.ar"},
{"sucursal":"35 – Tucuman (35)","nombre":"TORO Felix Daniel","puesto":"Jefe Operativo","interno":"35201","email":"dtoro@bancoindustrial.com.ar"},
{"sucursal":"35 – Tucuman (35)","nombre":"MAS VALDECANTOS Juan","puesto":"","interno":"35204","email":"jmas@bancoindustrial.com.ar"},
{"sucursal":"36 – Mar del Plata Centro","nombre":"CARRERA  Maria Alejandra","puesto":"Tesorero de Sucursal","interno":"36201","email":"vacio"},
{"sucursal":"36 – Mar del Plata Centro","nombre":"LUNA Juan Pablo","puesto":"Jefe Operativo","interno":"36200","email":"jluna@bancoindustrial.com.ar"},
{"sucursal":"36 – Mar del Plata Centro","nombre":"TALIERCIO DI IORIO Antonela","puesto":"","interno":"36205","email":"ataliercio@bancoindustrial.com.ar"},
{"sucursal":"36 – Mar del Plata Centro","nombre":"PEINADO  Damián Camilo Ernesto","puesto":"Gerente de Sucursal","interno":"36200","email":"dpeinado@bancoindustrial.com.ar"},
{"sucursal":"37 – La Plata Ctro (37)","nombre":"DE MARIA  Adolfo","puesto":"Jefe Operativo","interno":"221 489 4353","email":"ademaria@bancoindustrial.com.ar"},
{"sucursal":"37 – La Plata Ctro (37)","nombre":"DOMINGUEZ  Julio César","puesto":"Tesorero de Sucursal","interno":"221 489 4353","email":"jdominguez@bancoindustrial.com.ar"},
{"sucursal":"37 – La Plata Ctro (37)","nombre":"QUATTRINI  Walter Hector","puesto":"Gerente de Sucursal","interno":"221 489 4353","email":"wquatrini@bancoindustrial.com.ar"},
{"sucursal":"42 – Castelar","nombre":"CARERI Miguel Angel","puesto":"Tesorero de Sucursal","interno":"4483 5492","email":"vacio"},
{"sucursal":"42 – Castelar","nombre":"RODRIGUEZ Mirna Angela","puesto":"Gerente de Centro de Servicios","interno":"4483 5492","email":"marodriguez@bancoindustrial.com.ar"},
{"sucursal":"43 – Santos Lugares","nombre":"PRALONG  Vivian Karina","puesto":"Responsable de Centro de Servicios","interno":"4859 6264","email":"vpralong@bancoindustrial.com.ar"},
{"sucursal":"43 – Santos Lugares","nombre":"SANTOS  Matias Damian","puesto":"Tesorero de Sucursal","interno":"4859 6264","email":"msantos@bancoindustrial.com.ar"},
{"sucursal":"44 – Ciudadela","nombre":"DAVALOS Lis Vanesa","puesto":"Responsable de Centro de Servicios","interno":"4488 8032","email":"ldavalos@bancoindustrial.com.ar"},
{"sucursal":"44 – Ciudadela","nombre":"MACEDO Lucas","puesto":"Tesorero de Sucursal","interno":"4488 8032","email":"lmacedo@bancoindustrial.com.ar"},
{"sucursal":"44 – Ciudadela","nombre":"BOLLE Natalia","puesto":"","interno":"4488 8032","email":"nbolle@bancoindustrial.com.ar"},
{"sucursal":"45 – Ituzaingo","nombre":"CHAMORRO SMITH  Cristian Josue","puesto":"Jefe de Area","interno":"4623 1762","email":"cchamorro@bancoindustrial.com.ar"},
{"sucursal":"45 – Ituzaingo","nombre":"FROMBACH  Federico","puesto":"Gerente de Centro de Servicios","interno":"4623 1762","email":"ffrombach@bancoindustrial.com.ar"},
{"sucursal":"45 – Ituzaingo","nombre":"GIMENEZ  Federico Gaspar","puesto":"Tesorero de Sucursal","interno":"4623 1762","email":"fgimenez@bancoindustrial.com.ar"},
{"sucursal":"46 – Villa Mitre","nombre":"AZCONA Silvina","puesto":"Jefe Operativo","interno":"291 481 9894","email":"sazcona@bancoindustrial.com.ar"},
{"sucursal":"46 – Villa Mitre","nombre":"RESCHKE Ivanna","puesto":"","interno":"291 481 9894","email":"ireschke@bancoindustrial.com.ar"},
{"sucursal":"47 – Villa Insuperable","nombre":"LEBRON Mariano","puesto":"Gerente de Centro de Servicios","interno":"4454 4440","email":"vbazzano@bancoindustrial.com.ar"},
{"sucursal":"47 – Villa Insuperable","nombre":"SANTILLAN  Angel Mariano","puesto":"Tesorero de Sucursal","interno":"4454 4440","email":"asantillan@bancoindustrial.com.ar"},
{"sucursal":"48 – San Pedro","nombre":"FACCHINI  Andres Marcos","puesto":"Gerente de Centro de Servicios","interno":"3329 42 8516","email":"afacchini@bancoindustrial.com.ar"},
{"sucursal":"48 – San Pedro","nombre":"PRATS  Ariel","puesto":"Tesorero de Sucursal","interno":"3329 42 8516","email":"aprats@bancoindustrial.com.ar"},
{"sucursal":"49 – Loma Hermosa","nombre":"CALLEJO  Matias Daniel","puesto":"Tesorero de Sucursal","interno":"4841 5295","email":"mcallejo@bancoindustrial.com.ar"},
{"sucursal":"49 – Loma Hermosa","nombre":"SERGIO  Claudio Fabian","puesto":"Gerente de Centro de Servicios","interno":"4841 5295","email":"csergio@bancoindustrial.com.ar"},
{"sucursal":"50 – Cordoba Sucre","nombre":"FERREYRA PATIÑO  Francisco","puesto":"Tesorero de Sucursal","interno":"351 411 3683","email":"vacio"},
{"sucursal":"50 – Cordoba Sucre","nombre":"GALLIUSSI  Adrian Carlos","puesto":"Gerente de Centro de Servicios","interno":"351 411 3683","email":"agalliussi@bancoindustrial.com.ar"},
{"sucursal":"50 – Cordoba Sucre","nombre":"ROBLES  Maria Soledad","puesto":"Jefe Operativo","interno":"351 411 3683","email":"mrobles@bancoindustrial.com.ar"},
{"sucursal":"51 – Tucuman Centro","nombre":"PATA  María Soledad","puesto":"Gerente de Centro de Servicios","interno":"381 411 1288","email":"mpata@bancoindustrial.com.ar"},
{"sucursal":"51 – Tucuman Centro (51)","nombre":"REDONDO  Josefina del Carmen","puesto":"Jefe de Area","interno":"381 411 1288","email":"jredondo@bancoindustrial.com.ar"},
{"sucursal":"51 – Tucuman Centro (51)","nombre":"SOSA  Oscar Rolando","puesto":"Tesorero de Sucursal","interno":"381 411 1288","email":"vacio"},
{"sucursal":"52 – La Plata (52)","nombre":"IVORRA  Miguel Angel","puesto":"Responsable de Centro de Servicios","interno":"221 453 6541","email":"mivorra@bancoindustrial.com.ar"},
{"sucursal":"52 – La Plata (52)","nombre":"OCHOA  Ruben Jorge","puesto":"Tesorero de Sucursal","interno":"221 453 6541","email":"rjochoa@bancoindustrial.com.ar"},
{"sucursal":"53 – Tigre (53)","nombre":"HERGENREDER  Guillermo Oscar","puesto":"Tesorero de Sucursal","interno":"4005 0248","email":"vacio"},
{"sucursal":"53 – Tigre (53)","nombre":"RAFFAGHELLO  Alejandra Vanesa","puesto":"Responsable de Centro de Servicios","interno":"4005 0248","email":"araffaghello@bancoindustrial.com.ar"},
{"sucursal":"54 – Gaona","nombre":"GONZALEZ  Ricardo Luis","puesto":"Tesorero de Sucursal","interno":"4581 0212","email":"vacio"},
{"sucursal":"54 – Gaona","nombre":"PIGUES  Matias Daniel","puesto":"Responsable de Centro de Servicios","interno":"4581 0212","email":"mpigues@bancoindustrial.com.ar"},
{"sucursal":"54 – Gaona","nombre":"SEIDEL  Fabian Alejandro","puesto":"Tesorero de Sucursal","interno":"4581 0212","email":"fseidel@bancoindustrial.com.ar"},
{"sucursal":"55 – Ituzaingo (55)","nombre":"GONZALEZ MOLLER  Alejandro","puesto":"Tesorero de Sucursal","interno":"4624 7213","email":"agonzalezmoller@bancoindustrial.com.ar"},
{"sucursal":"55 – Ituzaingo (55)","nombre":"KORUÑAK  Daniela Maria","puesto":"Responsable de Centro de Servicios","interno":"4624 7213","email":"dkorunak@bancoindustrial.com.ar"},
{"sucursal":"99 – Nodo Pilar","nombre":"BRUNETTA  Maximiliano","puesto":"Gerente Nodo Empresas","interno":"N/A","email":"vacio"}];
	})

